## prepGIGhis---------------------------2022-05-19
##  Prepare GIG Historical survey data.
##  survey==8  -- using Norm Olsen's grouping codes
##  survey==11 -- using Paul Starr's strata
## -----------------------------------------PJS|RH
prepGIGhis <- function(file, survey="GIGhis")
{
	surveyname = "GIG Historical"
	ttput(surveyname)
	ttput(survey)
	ttget(gfbsurvey)

	dat    = getLabels(file)
	ttget(stratum)
	label  = attributes(dat)$label ## keep temporarily just to be safe

	dat   = doSynoptic(dat, survey) ## even though it's not synoptic, function has some standardising routines

	#if (survey==8) { ## use Norm Olsen grouping codes when $survey==8 
	if (all(gfbsurvey[[survey]]==8)) { ## use Norm Olsen grouping codes when $survey==8 
		expr = expression(dat[!is.element(dat$reason,9),]) ## drop 19 tows in 1994 specified as target strength acoustic tows
		dat  = keepAtts(dat, expr)
		#dat$stratum[is.element(dat$reason,9)] = NA  ## drop 19 tows in 1994 specified as target strength acoustic tows
	}
	#else if (survey==11) {  ## define PJS strata for $survey==11: GIG lies within this latitude range
	else if (all(gfbsurvey[[survey]]==21)) {  ## define PJS strata for $survey==11: GIG lies within this latitude range
		#dat$stratum[dat$latitude>=50.9 & dat$latitude<=51.6 & !is.na(dat$latitude)] = 1
		expr = expression(dat[dat$latitude>=50.9 & dat$latitude<=51.6 & !is.na(dat$latitude),])
		dat  = keepAtts(dat, expr)
		#dat$stratum[is.element(dat$year, c(1965,1966,1979))] = NA
		## 1965 & 1966: wide-ranging exploratory; 1979: different design spatially; 1995: random instead of fixed stations
		expr = expression(dat[!is.element(dat$year, c(1965,1966,1979,1995)),])
		dat  = keepAtts(dat, expr)
		#dat$stratum[is.element(dat$reason,9)] = NA                ## drop 19 tows in 1994 specified as target strength acoustic tows
		expr = expression(dat[!is.element(dat$reason,9),]) ## drop 19 tows in 1994 specified as target strength acoustic tows
		dat  = keepAtts(dat, expr)
		#expr = expression(dat[dat$year>2002 & !is.na(dat$year),]) ## drop recent QC Snd synoptic survey Viking Storm tows
		#dat  = keepAtts(dat, expr)
		#dat$stratum2 = rep(0,nrow(dat))
		#dat$stratum2[dat$latitude>=50.9 & dat$latitude<=51.6  & !is.na(dat$latitude)] =1
		## lab var stratum2 "GIG flag: all surveys"
	}

	## The following code has already been dealt with by subfunction 'fixmiss' in 'doSynoptic'
	## For GIG Historical, effort and distance are better represented than door and speed; therefore, just fix the latter two.
	note = list()
	note[["author"]] = "Paul J. Starr"
	#note[["speed_old"]] = c(
	#	"This field is the original speed information: only one year with a mean>11 km/h.",
	#	"Provisionally not used because seems very high and not credible." )
	#dat$door  = ttcall(defaultdoorspread)  ## 61.6 m  vs. dat's 14.3 m
	#dat$speed = rep(NA, nrow(dat))
	#dat$speed = dat$distance / dat$effort

	#dat$density = dat$weight / (dat$distance * dat$door/1000.)
	#dat$density[is.na(dat$density)] = 0

	## Restratify using depint
	#lodep = as.numeric(attributes(depint)$labelends$low)
	#updep = as.numeric(attributes(depint)$labelends$upp)
	#dat$depstrat = sapply(dat$sdepth, function(mm){ zz = mm >= lodep & mm < updep; if(!any(zz)) NA else (1:length(depint))[zz] },simplify=TRUE)
	#dat$depint   = sapply(dat$sdepth, function(mm){ zz = mm >= lodep & mm < updep; if(!any(zz)) NA else depint[zz] },simplify=TRUE)
	### Get rid of the bad usability codes (e.g.9)  and non-GIG tows
	#badstrat = is.na(dat$stratum)
	#dat$depstrat[badstrat] = dat$depint[badstrat] = NA

	#if (survey==11) {
	#if (all(gfbsurvey[[survey]]==21)) {
	#	names(stratum) = c("Valid GIG tow", "", "")
	#	stratum2 = 0:1
	#	names(stratum2) = c("Outside GIG", "GIG tow")
	#}
	if (all(gfbsurvey[[survey]]==8)) {
		note[["GIG survey 8"]] =c(
			"This is a file of the Historical GIG survey data in Queen Charlotte Sound from 'minyear' to 'maxyear'.",
			"All 'ntows' tows in this file are deemed GIG tows within the correct latitude and depth range ('nvess' vessels in this file)"
		)
		note[["stratum"]] = "Generated from grouping code (stratum code generated by Norm Olsen for 'ntows' records in Goose Island Gully: 1967-1995 surveys only)"
		note[["area"]] = "Provided by N Olsen (Dec 2009) for strata 1 to 3, bounded by depth, for the three grouping codes."
	}
	else if (all(gfbsurvey[[survey]]==21)) {
		note[["GIG survey 11"]] =c(
			"This is a file of the Historical GIG GB Reed survey data in Queen Charlotte Sound from 'minyear' to 'maxyear'.",
			"Contains all tows from 'nvess' vessels that have surveyed in QC Sound ('ntows' tows).",
			"Viking Storm tows from the QC Sound Synoptic survey have been dropped."
		)
		note[["stratum"]]  = "set ==1 if lies between 50.9 and 51.6 with a valid usability code (0/1/2/6)."
		note[["stratum2"]] = "GIG flag for all surveys (ignore useflag and bad survey years)."
	}
	note[["catch"]] = paste0("The only catch data are for ", ttcall(speciesname), ".")
	note[["door"]]  = paste0("Assumed value (used ", ttcall(defaultdoorspread), "m = from Yamanaka et al. 1996 Can MS Report 2362)")
	note[["speed"]] = c(
		"Generated from small number of credible 'distance_travelled' records:",
		"speed = distance/time when present,",
		"speed = mean(speed) when missing."
		)
	note[["distance"]] = c(
		paste0("There were ", nrow(dat)-countVec(dat$distance_old), " records where distance==0."),
		"These were changed to mean values by year and stratum using subfunction 'fixmiss' in 'doSynoptic' before all calculations.",
		"Originally PJS calculated field: gen distance = effort*speed if distance==.",
		"Replace missing calculated distance records (ie when time==.) with mean distance for the year."
		)
	note[["depint"]] = c(
		"gen int depint=recode(sdepth, 146,183,219,256,292,329,366,402,440) ",
		"[this preserves 20 fathom intervals from 80 to 240 fathoms and then a catchall from 240 to deepest]"
		)

	## Choose fields for data return
	if (!is.null(ttcall(gigflds))){
		ttget(gigflds)
		outflds = intersect(gigflds, colnames(dat))
	} else {
		.flush.cat("All data fields will be returned.\n\tRun 'prepGFsurv' to get a standard subset of fields.\n\n")
		outflds = colnames(dat)
	}
	expr = expression(dat[,outflds])
	dat  = keepAtts(dat, expr, extras=list(outflds=outflds))

	attr(dat,"label") = label
	attr(dat,"note")  = note
	return(dat)
}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~prepGIGhis
