## prepHSass----------------------------2022-05-17
##  Prepare Hecate Strait assemblage survey data.
## -----------------------------------------PJS|RH
prepHSass <- function(file, survey="HSass")
{
	surveyname = "Hecate Strait Assemblage"
	ttput(surveyname)
	ttput(survey)

	stratum = 1:7
	names(stratum) = c("10-19 fm", "20-29 fm", "30-39 fm", "40-49 fm", "50-59 fm", "60-69 fm", "70-79 fm")
	attr(stratum,"labelends") = getLabelends(labelname=names(stratum))
	ttput(stratum)

	dat   = doSynoptic(dat, survey) ## even though it's not synoptic, function has some standardising routines
	label = attributes(dat)$label    ## add later as there is a lot of fiddly manipulation that follows

	## Note: 1984 had two trips operating.  This resets the set numbers and means
	##   that only year and set will determine all the records
	zset = is.element(dat$year,1984) & is.element(dat$trip,38645)
	dat$set[zset] = dat$set[zset] + 89
	dat  = dat[,setdiff(colnames(dat), c("species", "effort2", "wing", "open"))] #"door"
	dat  = dat[dat$year<=2003 & !is.na(dat$year),]

	## Restratify (note stratum boundaries are in metres: 10 fathoms=18.293 m; 20 f=36.586 m; etc...)
	dat$stratum_old = dat$stratum
	lodep = c(18.293, 36.586, 54.879, 73.172, 91.465, 109.758, 128.051)  ## in metres
	updep = c(36.586, 54.879, 73.172, 91.465, 109.758, 128.051, 146.344) ## in metres
	## Depths in SQL extraction from GFBioSQL are in metres
#browser();return()
	#dat$stratum = sapply(dat$sdepth, function(mm){ zz = mm >= lodep & mm < updep; print(zz); if(all(is.na(zz)) || !any(zz)) NA else stratum[zz] },simplify=TRUE)
	dat$stratum = sapply(dat$sdepth, function(mm){ zz = mm >= lodep & mm < updep; if(all(is.na(zz)) || !any(zz)) NA else stratum[zz] },simplify=TRUE)
	## Individual tweaks
	dat$stratum[is.na(dat$stratum) & (dat$sdepth<18.3 & !is.na(dat$sdepth))]  = 1  ## add one tow at 18 m
	dat$stratum[is.na(dat$stratum) & (dat$sdepth<148.3 & !is.na(dat$sdepth))] = 7  ## add two tows at 148 m

	## Overwrite stratum areas
	areas = c(2657, 1651, 908, 828, 912, 792, 612)
	zstra = !is.na(dat$stratum)
	dat$area_old = dat$area
	dat$area     = rep(NA, nrow(dat))
	dat$area[zstra] = areas[dat$stratum[zstra]]

	width  = 43/3280  ## wingspread is 43 ft> convert to kilometres
	speedy = crossTab(dat[is.element(dat$year,2002:2003),,drop=FALSE],c("year"),"speed", mean, na.rm=TRUE)
	zspeed = is.element(dat$year,2002:2003) & is.na(dat$speed)
	if (any(zspeed))
		dat$speed[zspeed] = speedy[as.character(dat$year[zspeed])]
	zdist = (dat$year>=2000 & !is.na(dat$year)) & is.na(dat$distance)
	if (any(zdist))
		dat$distance[zdist] = dat$speed[zdist] * dat$effort[zdist]
	dat$density = dat$weight / (dat$distance * width)
	dat$density[is.na(dat$density) & !is.na(dat$distance) & dat$year>=2000] = 0

	nunits = 1/0.0486
	dat$cpue = nunits * dat$weight / dat$effort  ## convert into density as suggested by Sinclair, page 11, penultimate para
	dat$cpue[is.na(dat$cpue)] = 0

	## The following reproduces what is in the ROL 2005 ResDoc
	dat$door[is.na(dat$door)]   = 43
	dat$speed[is.na(dat$speed)] = 5.1
	dat$distance[is.na(dat$distance)] = dat$speed * dat$effort
	dat$density = dat$weight / (dat$distance * dat$door/1000.)
	dat$density[is.na(dat$density)]   = 0

	note = list()
	note[["author"]] = "Paul J. Starr"
	note[["source"]] = paste0("This is a file of the Hecate Strait survey data from 1984 to 2003. The only catch data are for ", ttcall(speciesname), ".",
		"This file has all the survey tows and reasonably closely resembles the information in Sinclair (PSARC 99-196e)")
	note[["caveat"]] = "I could not reproduce exactly the distribution of tows shown in Table 6 of PSARC 99-196e.  Not sure why: tried basing the definition on the start depth, end depth, and the mean of the start and end depths.  Part of the problem is that the depths are in metres and the depth stratum definition are in fathoms.  I suspect that there is a unit conversion problem here and possibly a precision issue on the conversion.  All work is shown in function 'prepHSass'."
	note[["stratum"]] = "Stratum definition based on the depth at the start of the tow."
	note[["speed"]] = "Filled in 6 missing values in 2002 and 4 missing values in 2003 with mean speed for each year."
	note[["distance"]] = "Filled in missing values in 2002 and 2003 using speed*effort (=time towed). There were no missing distance values in 2000."
	note[["density"]] = "Calculated only from 2000 onward (density=weight/(distance*0.01311 km) where 0.01311=43 ft/3280 ft/km."
	note[["grouping"]] = "Code generated by Norm Olsen.  Conforms exactly to the definition of stratum by PJS"
	note[["stratum"]] = c(note[["stratum"]], "Added one tow at 18 m (just above 10 fathoms) to stratum 1. Added two tows at 148 m (just below 79 fathoms) to stratum 7. This field is missing ('.') for usability codes other than 0/1/6/.")
	note[["grouping"]] = c(note[["grouping"]], paste0("Original grouping code for all tows: ", texThatVec(.su(dat$group),simplify=FALSE)))

	## Choose fields for data return
	if (!is.null(ttcall(assflds))){
		ttget(assflds)
		outflds = intersect(assflds, colnames(dat))
	} else {
		.flush.cat("All data fields will be returned.\n\tRun 'prepGFsurv' to get a standard subset of fields.\n\n")
		outflds = colnames(dat)
	}
	expr = expression(dat[,outflds])
	dat  = keepAtts(dat, expr, extras=list(outflds=outflds))

	attr(dat,"label") = label
	attr(dat,"note")  = note
#browser();return()
	return(dat)
}
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~prepHSass
